version: '3'

services:
  mysql:
    container_name: xiaoshuo-mysql
    image: mysql:5.5
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123qweASD
  php:
    container_name: xiaoshuo-php
    image: shangxian/xiaoshuo-php:latest
    build: ./php
    restart: always
    volumes:
      - "${WWWROOT_DIR}/xiaoshuo.io:/var/www/html"

networks:
  default:
    external:
      name: "${DOCKER_PRIVATE_NETWORK_NAME}"
