version: '3'

services:
  mysql:
    container_name: xiaoshuo-mysql
    image: mysql:5.5
    environment:
        - MYSQL_ROOT_PASSWORD=123qweASD
  php:
    container_name: xiaoshuo-php
    image: shangxianapp/xiaoshuo-php:latest
    build: ./php
    restart: always
    volumes:
      - ./html:/usr/share/html

networks:
  default:
    external:
      name: "${DOCKER_PRIVATE_NETWORK_NAME}"